# DataProfiler CLI - Clippy configuration

# Avoid false positives for arithmetic operations
avoid-breaking-exported-api = false

# Allow some common patterns in data processing
doc-valid-idents = ["DataProfiler", "CSV", "JSON", "HTML", "API", "CLI", "MSRV"]

# Performance-focused lints
cognitive-complexity-threshold = 25
type-complexity-threshold = 100

# Allow longer functions for data processing logic
too-many-lines-threshold = 150

# String and formatting
max-fn-params-bools = 2
trivial-copy-size-limit = 128