# Codecov Configuration for DataProf
# https://docs.codecov.io/docs/codecov-yaml

# Coverage configuration
coverage:
  precision: 2  # 2 decimal places
  round: down
  range: "70...100"  # Red below 70%, green at 100%

  status:
    # Overall project coverage
    project:
      default:
        target: 75%  # Target coverage
        threshold: 2%  # Allow 2% drop without failing
        base: auto
        flags:
          - unittests
        if_not_found: success
        if_ci_failed: error

    # Patch coverage (code changed in PR)
    patch:
      default:
        target: 70%  # Lower target for new code
        threshold: 5%
        base: auto
        if_not_found: success
        if_ci_failed: error

# Comment on PRs
comment:
  layout: "diff, files, footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  branches:
    - master
    - main

# Ignore patterns
ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "examples/**/*"
  - "src/main.rs"
  - "src/python.rs"
  - "target/**/*"
  - "**/*.md"
  - ".github/**/*"
  - "scripts/**/*"

# Flags for different test types
flags:
  unittests:
    paths:
      - src/
    carryforward: true

# GitHub checks
github_checks:
  annotations: true
