# cargo-deny configuration for DataProfiler
# Install with: cargo install cargo-deny
# Run with: cargo deny check

[graph]
# All feature combinations for more thorough checking
all-features = true

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Unlicense",
    "Zlib",
]

# Confidence threshold for detecting a license from a license file.
# Licenses with a confidence score lower than this threshold will be ignored.
confidence-threshold = 0.8

# Allow 1 or more licenses on a per-crate basis, so that particular licenses
# aren't accepted for every possible crate as with the normal allow list
exceptions = [
    # Some specific dependencies that have known good licenses not in our main list
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["BSL-1.0"], name = "ryu" },
]

# Lint level for when multiple versions of the same license are detected
multiple-versions = "warn"

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# Allow certain duplicate dependencies that are hard to avoid
skip = [
    # Different versions of these are often pulled in by different dependencies
    { name = "windows-sys" },
    { name = "windows_x86_64_msvc" },
    { name = "bitflags" },
]

# Skip certain crates when checking for duplicates
skip-tree = [
    # Skip Windows-specific dependencies that often have duplicates
    { name = "windows-sys" },
]

# List of explicitly disallowed crates
deny = [
    # Crates with known security issues or that are deprecated
    { name = "openssl", reason = "Use rustls instead for better security" },
    { name = "native-tls", reason = "Use rustls-tls for better cross-platform support" },
]

# Certain crates that are deprecated but we might want to allow temporarily
allow = [
    # Add specific crates here if needed temporarily
]

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]

# The lint level for security vulnerabilities
vulnerability = "deny"

# The lint level for unmaintained crates
unmaintained = "warn"

# The lint level for crates that have been yanked from their source registry
yanked = "warn"

# The lint level for crates with security notices
notice = "warn"

# A list of advisory IDs to ignore.
ignore = [
    # RSA Marvin Attack - no fix available yet
    "RUSTSEC-2023-0071",
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"

# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"

# List of allowed registries
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
]

# List of allowed Git repositories
allow-git = [
    # Add specific git dependencies here if needed
]