name: 'Setup System Dependencies'
description: 'Install DuckDB, SQLite and other system dependencies'

runs:
  using: composite
  steps:
    - name: Check if DuckDB is installed
      id: check-duckdb
      shell: bash
      run: |
        if [ -f "/usr/local/lib/libduckdb.so" ] && [ -f "/usr/local/include/duckdb.h" ]; then
          echo "duckdb-exists=true" >> $GITHUB_OUTPUT
        else
          echo "duckdb-exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Install system dependencies
      if: steps.check-duckdb.outputs.duckdb-exists != 'true'
      shell: bash
      run: |
        echo "📦 Installing system dependencies..."
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev wget unzip

        # Install DuckDB from release
        echo "⬇️ Downloading DuckDB 1.1.3..."
        wget -q https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-linux-amd64.zip
        unzip -q libduckdb-linux-amd64.zip
        sudo cp libduckdb.so /usr/local/lib/
        sudo cp duckdb.h /usr/local/include/
        rm -f libduckdb-linux-amd64.zip libduckdb.so duckdb.h

        echo "✅ System dependencies installed"

    - name: Configure library paths
      shell: bash
      run: |
        sudo ldconfig
        echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "🔗 Library paths configured"
