name: 'Setup System Dependencies'
description: 'Install DuckDB, SQLite and other system dependencies'

runs:
  using: composite
  steps:
    - name: Cache system dependencies
      id: cache-sys-deps
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/lib/libduckdb.so
          /usr/local/include/duckdb.h
        key: system-deps-duckdb-1.1.3-${{ runner.os }}

    - name: Install system dependencies
      if: steps.cache-sys-deps.outputs.cache-hit != 'true'
      run: |
        echo "📦 Installing system dependencies..."
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev wget unzip

        # Install DuckDB from release
        echo "⬇️ Downloading DuckDB 1.1.3..."
        wget -q https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-linux-amd64.zip
        unzip -q libduckdb-linux-amd64.zip
        sudo cp libduckdb.so /usr/local/lib/
        sudo cp duckdb.h /usr/local/include/
        rm -f libduckdb-linux-amd64.zip libduckdb.so duckdb.h

        echo "✅ System dependencies installed"
      shell: bash

    - name: Configure library paths
      run: |
        sudo ldconfig
        echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "🔗 Library paths configured"
      shell: bash